#!/usr/bin/env python

import subprocess
import sys
import os.path


FILE_COMMAND_TEST = 'run_tests.sh'


def run_tests(filepath):
    test_command = 'sh %s' % filepath
    process = subprocess.Popen(test_command,
                               stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT,
                               shell=True)
    process.wait()
    return process.returncode


if __name__ == '__main__':
    if not os.path.exists(FILE_COMMAND_TEST):
        print('Pre-commit hook not run! No such file "%s"!' %
              FILE_COMMAND_TEST)
        sys.exit(1)
    print('Please wait. Testing...')
    return_code = run_tests(FILE_COMMAND_TEST)
    if return_code == 0:
        print('Tests completed successfully.')
    else:
        print('Some of tests are failed. Check tests before do commit.')
    sys.exit(return_code)
