#!/usr/bin/env python

import subprocess
import sys
import re


TEST_COMMAND = 'sh run_tests.sh'


def run_tests():
    print('Please wait. Testing...')
    try:
        process = subprocess.Popen(TEST_COMMAND,
                                   stdin=None,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.STDOUT,
                                   shell=True,
                                   universal_newlines=True
                                   )
        output = process.communicate(None)[0]
    except Exception, e:
        raise e
    failures = re.findall(r'(?<=failures\=)\d+', output)
    failures += re.findall(r'[EW]\d+', output)
    if not failures:
        print('Tests completed successfully.')
    else:
        print('Some of tests are failed. Check tests before do commit.')
        sys.exit(1)

if __name__ == '__main__':
    run_tests()
